### ISSUE TITLE
error: unable to recognize "XXX.yaml": no matches for kind "NetworkAttachmentDefinition" in version "k8s.cni.cncf.io/v1"

### ISSUE THREAD

**Issue by heng-Yuan** [intel/multus-cni#447] opened 2020-03-04 09:19 UTC
```
[root@kingslanding4 mori]# kubectl get crd network-attachment-definitions.k8s.cni.cncf.io -o yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"name":"network-attachment-definitions.k8s.cni.cncf.io"},"spec":{"group":"k8s.cni.cncf.io","names":{"kind":"NetworkAttachmentDefinition","plural":"network-attachment-definitions","shortNames":["net-attach-def"],"singular":"network-attachment-definition"},"scope":"Namespaced","versions":[{"name":"v1","schema":{"openAPIV3Schema":{"properties":{"spec":{"properties":{"config":{"type":"string"}},"type":"object"}},"type":"object"}},"served":true,"storage":true}]}}
  creationTimestamp: "2020-03-04T08:39:02Z"
  generation: 1
  name: network-attachment-definitions.k8s.cni.cncf.io
  resourceVersion: "19101"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/network-attachment-definitions.k8s.cni.cncf.io
  uid: bde44267-4f35-4912-8394-7794ac69a6bf
spec:
  conversion:
    strategy: None
  group: k8s.cni.cncf.io
  names:
    kind: NetworkAttachmentDefinition
    listKind: NetworkAttachmentDefinitionList
    plural: network-attachment-definitions
    shortNames:
    - net-attach-def
    singular: network-attachment-definition
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              config:
                type: string
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: NetworkAttachmentDefinition
    listKind: NetworkAttachmentDefinitionList
    plural: network-attachment-definitions
    shortNames:
    - net-attach-def
    singular: network-attachment-definition
  conditions:
  - lastTransitionTime: "2020-03-04T08:39:02Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2020-03-04T08:39:02Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
```
I've created this **NetworkAttachmentDefinition** CRD ，
But, when I was created this NetworkAttachmentDefinition resource,  I've got this error:
```
[root@kingslanding4 mori]# kubectl apply -f network-attach-macvlan-static.yaml 
error: unable to recognize "network-attach-macvlan-static.yaml": no matches for kind "NetworkAttachmentDefinition" in version "k8s.cni.cncf.io/v1"

```
```
[root@kingslanding4 mori]# cat network-attach-macvlan-static.yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf-static
spec:
  config: '{
            "cniVersion": "0.3.0",
            "type": "macvlan",
            "master": "bond0",
            "mode": "bridge",
            "ipam": {
                "type": "static"
            }
        }'
```

And , I couldn't get this api use `kubectl api-verions` :
```
[root@kingslanding4 mori]# kubectl api-versions
admissionregistration.k8s.io/v1
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1
apiregistration.k8s.io/v1beta1
apps/v1
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1
autoscaling/v2beta2
batch/v1
batch/v1beta1
certificates.k8s.io/v1beta1
coordination.k8s.io/v1
coordination.k8s.io/v1beta1
crd.projectcalico.org/v1
discovery.k8s.io/v1beta1
events.k8s.io/v1beta1
extensions/v1beta1
networking.k8s.io/v1
networking.k8s.io/v1beta1
node.k8s.io/v1beta1
policy/v1beta1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
scheduling.k8s.io/v1
scheduling.k8s.io/v1beta1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1
```
Furthermore, I also can't find metrics-server crd api.

But , I can get this api use local proxy:
```
[root@kingslanding4 ~]# kubectl proxy --port=8080
Starting to serve on 127.0.0.1:8080


[root@kingslanding4 mori]# curl localhost:8080/apis
{
  "kind": "APIGroupList",
  "apiVersion": "v1",
  "groups": [
    {
      "name": "apiregistration.k8s.io",
      "versions": [
        {
          "groupVersion": "apiregistration.k8s.io/v1",
          "version": "v1"
        },
        {
          "groupVersion": "apiregistration.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "apiregistration.k8s.io/v1",
        "version": "v1"
      }
    },
    ...

    ...

    {
      "name": "k8s.cni.cncf.io",
      "versions": [
        {
          "groupVersion": "k8s.cni.cncf.io/v1",
          "version": "v1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "k8s.cni.cncf.io/v1",
        "version": "v1"
      }
    },
    {
      "name": "metrics.k8s.io",
      "versions": [
        {
          "groupVersion": "metrics.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "metrics.k8s.io/v1beta1",
        "version": "v1beta1"
      }
    }
  ]
}
```

And，
```
[root@kingslanding4 mori]# kubectl get networkattachmentdefinition.k8s.cni.cncf.io --v=10
I0304 17:10:06.271613  158737 loader.go:375] Config loaded from file:  /root/.kube/config
I0304 17:10:06.272693  158737 cached_discovery.go:114] returning cached discovery info from /root/.kube/cache/discovery/172.16.201.12_6443/servergroups.json
I0304 17:10:06.274372  158737 cached_discovery.go:71] returning cached discovery info from /root/.kube/cache/discovery/172.16.201.12_6443/v1/serverresources.json
...

I0304 17:10:06.283186  158737 round_trippers.go:423] curl -k -v -XGET  -H "User-Agent: kubectl/v1.17.0 (linux/amd64) kubernetes/70132b0" -H "Accept: application/json, */*" 'https://172.16.201.12:6443/apis?timeout=32s'
I0304 17:10:06.283291  158737 round_trippers.go:443] GET https://172.16.201.12:6443/apis?timeout=32s 200 OK in 0 milliseconds
I0304 17:10:06.283314  158737 round_trippers.go:449] Response Headers:
I0304 17:10:06.283336  158737 round_trippers.go:452]     X-From-Cache: 1
I0304 17:10:06.283356  158737 round_trippers.go:452]     Content-Type: application/json
I0304 17:10:06.283375  158737 round_trippers.go:452]     Date: Wed, 04 Mar 2020 21:54:25 GMT
I0304 17:10:06.283451  158737 request.go:1017] Response Body: 
{
  "kind": "APIGroupList",
  "apiVersion": "v1",
  "groups": [
    {
      "name": "apiregistration.k8s.io",
      "versions": [
        {
          "groupVersion": "apiregistration.k8s.io/v1",
          "version": "v1"
        },
        {
          "groupVersion": "apiregistration.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "apiregistration.k8s.io/v1",
        "version": "v1"
      }
    },
    {
      "name": "extensions",
      "versions": [
        {
          "groupVersion": "extensions/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "extensions/v1beta1",
        "version": "v1beta1"
      }
    },
    {
      "name": "apps",
      "versions": [
        {
          "groupVersion": "apps/v1",
          "version": "v1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "apps/v1",
        "version": "v1"
      }
    },
    {
      "name": "events.k8s.io",
      "versions": [
        {
          "groupVersion": "events.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "events.k8s.io/v1beta1",
        "version": "v1beta1"
      }
    },
    {
      "name": "authentication.k8s.io",
      "versions": [
        {
          "groupVersion": "authentication.k8s.io/v1",
          "version": "v1"
        },
        {
          "groupVersion": "authentication.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "authentication.k8s.io/v1",
        "version": "v1"
      }
    },
    {
      "name": "authorization.k8s.io",
      "versions": [
        {
          "groupVersion": "authorization.k8s.io/v1",
          "version": "v1"
        },
        {
          "groupVersion": "authorization.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "authorization.k8s.io/v1",
        "version": "v1"
      }
    },
    {
      "name": "autoscaling",
      "versions": [
        {
          "groupVersion": "autoscaling/v1",
          "version": "v1"
        },
        {
          "groupVersion": "autoscaling/v2beta1",
          "version": "v2beta1"
        },
        {
          "groupVersion": "autoscaling/v2beta2",
          "version": "v2beta2"
        }
      ],
      "preferredVersion": {
        "groupVersion": "autoscaling/v1",
        "version": "v1"
      }
    },
    {
      "name": "batch",
      "versions": [
        {
          "groupVersion": "batch/v1",
          "version": "v1"
        },
        {
          "groupVersion": "batch/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "batch/v1",
        "version": "v1"
      }
    },
    {
      "name": "certificates.k8s.io",
      "versions": [
        {
          "groupVersion": "certificates.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "certificates.k8s.io/v1beta1",
        "version": "v1beta1"
      }
    },
    {
      "name": "networking.k8s.io",
      "versions": [
        {
          "groupVersion": "networking.k8s.io/v1",
          "version": "v1"
        },
        {
          "groupVersion": "networking.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "networking.k8s.io/v1",
        "version": "v1"
      }
    },
    {
      "name": "policy",
      "versions": [
        {
          "groupVersion": "policy/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "policy/v1beta1",
        "version": "v1beta1"
      }
    },
    {
      "name": "rbac.authorization.k8s.io",
      "versions": [
        {
          "groupVersion": "rbac.authorization.k8s.io/v1",
          "version": "v1"
        },
        {
          "groupVersion": "rbac.authorization.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "rbac.authorization.k8s.io/v1",
        "version": "v1"
      }
    },
    {
      "name": "storage.k8s.io",
      "versions": [
        {
          "groupVersion": "storage.k8s.io/v1",
          "version": "v1"
        },
        {
          "groupVersion": "storage.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "storage.k8s.io/v1",
        "version": "v1"
      }
    },
    {
      "name": "admissionregistration.k8s.io",
      "versions": [
        {
          "groupVersion": "admissionregistration.k8s.io/v1",
          "version": "v1"
        },
        {
          "groupVersion": "admissionregistration.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "admissionregistration.k8s.io/v1",
        "version": "v1"
      }
    },
    {
      "name": "apiextensions.k8s.io",
      "versions": [
        {
          "groupVersion": "apiextensions.k8s.io/v1",
          "version": "v1"
        },
        {
          "groupVersion": "apiextensions.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "apiextensions.k8s.io/v1",
        "version": "v1"
      }
    },
    {
      "name": "scheduling.k8s.io",
      "versions": [
        {
          "groupVersion": "scheduling.k8s.io/v1",
          "version": "v1"
        },
        {
          "groupVersion": "scheduling.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "scheduling.k8s.io/v1",
        "version": "v1"
      }
    },
    {
      "name": "coordination.k8s.io",
      "versions": [
        {
          "groupVersion": "coordination.k8s.io/v1",
          "version": "v1"
        },
        {
          "groupVersion": "coordination.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "coordination.k8s.io/v1",
        "version": "v1"
      }
    },
    {
      "name": "node.k8s.io",
      "versions": [
        {
          "groupVersion": "node.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "node.k8s.io/v1beta1",
        "version": "v1beta1"
      }
    },
    {
      "name": "discovery.k8s.io",
      "versions": [
        {
          "groupVersion": "discovery.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "discovery.k8s.io/v1beta1",
        "version": "v1beta1"
      }
    },
    {
      "name": "crd.projectcalico.org",
      "versions": [
        {
          "groupVersion": "crd.projectcalico.org/v1",
          "version": "v1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "crd.projectcalico.org/v1",
        "version": "v1"
      }
    }
  ]
}
...
F0304 17:10:06.295728  158737 helpers.go:114] error: the server doesn't have a resource type "networkattachmentdefinition"
```
 I was found this HTTP Response doesn't have `k8s.cni.cncf.io/v1` and
`metrics.k8s.io/v1beta1` api group.

my envrionments:
os : 
[root@kingslanding4 mori]# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) for Fiberhome Server Linux version 3.10.0-693.el7.x86_64,CT (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) 

docker:
[root@kingslanding4 mori]# docker version
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:29:29 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:28:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

k8s version:
[root@kingslanding4 mori]# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by s1061123** [comment] 2020-03-04 09:45
I suppose that is not a multus issue, just a kubernetes issue.

To clarify it, could you please test to create simple CRD in k8s without error as following example?:

https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/


I also do repro with following environment, but I cannot reproduced it.

```
[centos@kube-master ~]$ cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)
[centos@kube-master ~]$ sudo crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.16.2-1.el7
RuntimeApiVersion:  v1alpha1
[centos@kube-master ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
[centos@kube-master ~]$ cat test.yml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: network-attachment-definitions.k8s.cni.cncf.io
spec:
  group: k8s.cni.cncf.io
  scope: Namespaced
  names:
    plural: network-attachment-definitions
    singular: network-attachment-definition
    kind: NetworkAttachmentDefinition
    listKind: NetworkAttachmentDefinitionList
    shortNames:
    - net-attach-def
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              config:
                type: string
[centos@kube-master ~]$ kubectl create -f test.yml
customresourcedefinition.apiextensions.k8s.io/network-attachment-definitions.k8s.cni.cncf.io created
[centos@kube-master ~]$ cat test3.yml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf-static
spec:
  config: '{
            "cniVersion": "0.3.0",
            "type": "macvlan",
            "master": "bond0",
            "mode": "bridge",
            "ipam": {
                "type": "static"
            }
        }'
[centos@kube-master ~]$ kubectl create -f test3.yml
networkattachmentdefinition.k8s.cni.cncf.io/macvlan-conf-static created
```

**Comment by heng-Yuan** [comment] 2020-03-04 09:59
> I suppose that is not a multus issue, just a kubernetes issue.
> 
> To clarify it, could you please test to create simple CRD in k8s without error as following example?:
> 
> https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/
> 
> I also do repro with following environment, but I cannot reproduced it.
> 
> ```
> [centos@kube-master ~]$ cat /etc/centos-release
> CentOS Linux release 7.6.1810 (Core)
> [centos@kube-master ~]$ sudo crictl version
> Version:  0.1.0
> RuntimeName:  cri-o
> RuntimeVersion:  1.16.2-1.el7
> RuntimeApiVersion:  v1alpha1
> [centos@kube-master ~]$ kubectl version
> Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
> [centos@kube-master ~]$ cat test.yml
> apiVersion: apiextensions.k8s.io/v1
> kind: CustomResourceDefinition
> metadata:
>   name: network-attachment-definitions.k8s.cni.cncf.io
> spec:
>   group: k8s.cni.cncf.io
>   scope: Namespaced
>   names:
>     plural: network-attachment-definitions
>     singular: network-attachment-definition
>     kind: NetworkAttachmentDefinition
>     listKind: NetworkAttachmentDefinitionList
>     shortNames:
>     - net-attach-def
>   versions:
>   - name: v1
>     served: true
>     storage: true
>     schema:
>       openAPIV3Schema:
>         type: object
>         properties:
>           spec:
>             type: object
>             properties:
>               config:
>                 type: string
> [centos@kube-master ~]$ kubectl create -f test.yml
> customresourcedefinition.apiextensions.k8s.io/network-attachment-definitions.k8s.cni.cncf.io created
> [centos@kube-master ~]$ cat test3.yml
> apiVersion: "k8s.cni.cncf.io/v1"
> kind: NetworkAttachmentDefinition
> metadata:
>   name: macvlan-conf-static
> spec:
>   config: '{
>             "cniVersion": "0.3.0",
>             "type": "macvlan",
>             "master": "bond0",
>             "mode": "bridge",
>             "ipam": {
>                 "type": "static"
>             }
>         }'
> [centos@kube-master ~]$ kubectl create -f test3.yml
> networkattachmentdefinition.k8s.cni.cncf.io/macvlan-conf-static created
> ```

Yes , it's a kubernetes issue. I followed [k8s example](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition) ,  And  it couldn't success. 
```
[root@kingslanding4 test_yaml]# curl localhost:8080/apis/stable.example.com/v1
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "stable.example.com/v1",
  "resources": [
    {
      "name": "crontabs",
      "singularName": "crontab",
      "namespaced": true,
      "kind": "CronTab",
      "verbs": [
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "create",
        "update",
        "watch"
      ],
      "shortNames": [
        "ct"
      ],
      "storageVersionHash": "EdX2FP+L0js="
    }
  ]
}

[root@kingslanding4 test_yaml]# kubectl apply -f my-crontab.yaml
error: unable to recognize "my-crontab.yaml": no matches for kind "CronTab" in version "stable.example.com/v1"
```
Do you know how to fix it?

**Comment by s1061123** [comment] 2020-03-04 14:11
I don't have any clear idea for that. How about to re-install kubernetes and try it again?

Let me close this issue.

**Closed by s1061123** 2020-03-04 14:11 UTC

**Comment by rsparulek** [comment] 2020-05-21 21:12
I am hitting this issue on an upgraded setup 1.16.9

**Comment by rsparulek** [comment] 2020-05-21 21:13
```
error: unable to recognize "multus.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
unable to recognize "multus-network-attachments.yaml": no matches for kind "NetworkAttachmentDefinition" in version "k8s.cni.cncf.io/v1"
unable to recognize "multus-network-attachments.yaml": no matches for kind "NetworkAttachmentDefinition" in version "k8s.cni.cncf.io/v1"
```

**Comment by cx-z** [comment] 2020-09-30 09:31
hey,guys. Have you solved this problem? I have the same issue now.请问博主可以把你后续的解决方案分享出来吗？

**Comment by cx-z** [comment] 2020-09-30 11:59
I had the same problem. Finally, I solved it by install multus-cni. You can refer to this artical: https://blog.csdn.net/u010827484/article/details/86824497#commentBox
