### ISSUE TITLE
Multus do no add default network to the pods

### ISSUE THREAD

**Issue by sbhojpur** [intel/multus-cni#134] opened 2018-08-24 12:12 UTC
I am using Weave and MacVlan in my cluster. Weave is my default network and i have created a CRD newtork MacVlan. Now when i try to spin a pod with annotation  referring only MacVlan, my pod come up with only MacVlan.
I was hoping to see both Weave and macVlan in the pod.

multus config-----
{
  "name": "minion-cni-network",
  "type": "multus",
  "kubeconfig": "/etc/kubernetes/node-kubeconfig.yaml",
  "delegates": [{
        "type": "weave-net",
        "hairpinMode": true,
        "masterplugin": true
  }]
}

pod manifest---
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    networks: '[
        { "name": "macvlan3-conf"}
    ]'

spec:
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network

**Comment by rkamudhan** [comment] 2018-08-29 16:18
@sbhojpur: The annotation is not correct.. Can you check the readme file.. It is not `networks` in your pod spec

**Comment by sbhojpur** [comment] 2018-08-31 04:08
@rkamudhan : I defined my CRD like below 
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: 2018-08-30T19:20:57Z
  generation: 1
  name: networks.kubernetes.com
  resourceVersion: "6630"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/networks.kubernetes.com
  uid: d24cca40-ac89-11e8-a4f5-d850e6d3cc29
spec:
  group: kubernetes.com
  names:
    kind: Network
    listKind: NetworkList
    plural: networks
    shortNames:
    - net
    singular: network
  scope: Namespaced
  version: v1

So i should be able to use api networks in annotation section of pod spec. 
Also i was able to assign macvlan based network to pod but not Weave.
So i am not sure if default network is assigned to pods in addition to the ones give in annotation.

**Comment by sbhojpur** [comment] 2018-08-31 04:17
From readme file 'Configurations referenced in annotations are created in addition to the default network.'
Is this statement correct? somehow i am not able to validate it.

**Comment by rkamudhan** [comment] 2018-08-31 14:17
can you share your Multus CNI conf file

**Comment by s1061123** [comment] 2018-08-31 14:27
@sbhojpur we would like to have debug log. Could you please add "logFile" and "logLevel" in your multus config (of /etc/cni/net.d/) and reproduce it with latest or v3.1? Then we get /var/log/multus.log so please put somewhere (like pastebin).

/etc/cni/net.d/multus.conf
```
{
   //YOUR multus config HERE
      "logFile": "/var/log/multus.log",
      "logLevel": "debug"
}
```

**Comment by s1061123** [comment] 2019-05-31 06:41
@sbhojpur hi, it is a quite long time to hold the issue since the last update, so let me close this issue. If you still have it, please re-open with debug log as I mentioned above ("logFile" and "logLevel" in cni config).

**Closed by s1061123** 2019-05-31 06:41 UTC
